export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_DATABASES_SUCCESS = "FETCH_DATABASES_SUCCESS";
export const FETCH_STORE_FUNC_NAME_SUCCESS = "FETCH_STORE_FUNC_NAME_SUCCESS";
export const FETCH_TABLE_NAME_SUCCESS = "FETCH_TABLE_NAME_SUCCESS";
export const FETCH_PROJECT_KAFKA_GRPC_SUCCESS =
  "FETCH_PROJECT_KAFKA_GRPC_SUCCESS";
export const FETCH_SERVICE_KAFKA_GRPC_SUCCESS =
  "FETCH_SERVICE_KAFKA_GRPC_SUCCESS";
export const FETCH_KAFKA_PROFILE_SUCCESS = "FETCH_KAFKA_PROFILE_SUCCESS";
